version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mymongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./etsisi_data:/data/db # Volumen para persistir datos
      - ./init.js:/docker-entrypoint-initdb.d/init.js # Script de inialización (opcional)
      - ./data.js:/docker-entrypoint-initdb.d/data.js # Datos iniciales (opcional)
    logging:
      driver: none